Numpy basics

In [1]:
import numpy as np

Using numpy

In [4]:
a = np.array([1, 2, 3], dtype='int8')
print(a)

[1 2 3]


In [26]:
b = np.array([
    [4, 3],
    [5, 6],
    [7, 11]
], dtype='int8')
b_1 = np.array([
    [2, 5, -1],
    [3, 5, -2],
], dtype='int8')
print(b)
print(b_1)
print(b.dot(b_1))

[[ 4  3]
 [ 5  6]
 [ 7 11]]
[[ 2  5 -1]
 [ 3  5 -2]]
[[ 17  35 -10]
 [ 28  55 -17]
 [ 47  90 -29]]


In [27]:
c = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
], dtype='uint8')
c_1 = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
], dtype='uint8')
c.dot(c_1)

array([[[[ 30,  36,  42],
         [ 30,  36,  42],
         [ 30,  36,  42]],

        [[ 66,  81,  96],
         [ 66,  81,  96],
         [ 66,  81,  96]],

        [[102, 126, 150],
         [102, 126, 150],
         [102, 126, 150]]],


       [[[ 30,  36,  42],
         [ 30,  36,  42],
         [ 30,  36,  42]],

        [[ 66,  81,  96],
         [ 66,  81,  96],
         [ 66,  81,  96]],

        [[102, 126, 150],
         [102, 126, 150],
         [102, 126, 150]]],


       [[[ 30,  36,  42],
         [ 30,  36,  42],
         [ 30,  36,  42]],

        [[ 66,  81,  96],
         [ 66,  81,  96],
         [ 66,  81,  96]],

        [[102, 126, 150],
         [102, 126, 150],
         [102, 126, 150]]]], dtype=uint8)