Numpy basics

In [1]:
import numpy as np

Using numpy

In [47]:
inputs = np.array(
    [1, 2, 3.5, 1.3]
)
weights = np.array([
    [0.2, 0.8, -1.2, 4.2],
    [-1.4, 3, 1.5, 0.6],
    [3.4, 1.6, -2, -2.3]
])
biases = np.array([2, 1.4, -1])

print(f'{inputs} - {inputs.shape}\n{weights.T} - {weights.T.shape}')
output: np.ndarray = np.dot(inputs, weights.T) + biases
print(f'Output: {output}')


[1.  2.  3.5 1.3] - (4,)
[[ 0.2 -1.4  3.4]
 [ 0.8  3.   1.6]
 [-1.2  1.5 -2. ]
 [ 4.2  0.6 -2.3]] - (4, 3)
Output: [ 5.06 12.03 -4.39]


In [52]:
def ReLU(x):
    return np.maximum(x, 0)

def softmax(x):
    return np.exp(x) / np.sum(np.exp(x))


class Layer:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))

    def forward(self, x):
        return np.dot(x, self.weights) + self.biases

layer1 = Layer(4, 5)
layer2 = Layer(5, 5)

output1 = layer1.forward(inputs)
output1 = ReLU(output1)
print(output1)
output2 = layer2.forward(output1)
output2 = softmax(output2)
print(output2, np.sum(output2))




[[0.52007233 0.15997478 0.         0.         0.        ]]
[[0.20473926 0.18441026 0.21379763 0.19218482 0.20486803]] 1.0


# Calculating Loss with Categorical Cross-Entropy

In [61]:
classes = 5
label = 2
target = [1, 0, 0, 0, 0]
output2 = np.array([0.7, 0.1, 0.1, 0.05, 0.05])

def loss(x):
    return -np.sum(np.array([np.log(x[i]) * target[i] for i in range(len(x))]))

print(loss(output2))

0.35667494393873245
0.35667494393873245
